version: '3'

services:
  web:
    build: .

    image: ubuntu-frontend

    container_name: webpack-app

    restart: always

    stdin_open: true

    tty: true

    ports:
      - "3000:3000"
      - "4000:4000"
      - "9000:9000"

    volumes:
      - "./app:/home/app"
